whitespace gets lost due to a conflict and we may need to rework this.
```js
  1) jsx-one-element-per-line invalid <Text style={styles.foo}>{ bar }
{ I18n.t('baz') }</Text>:

      AssertionError: Output is incorrect.
      + expected - actual

       <Text style={styles.foo}>
      -{ bar }
      -{ I18n.t('baz') }</Text>
      +{ bar }
      +{' '}{ I18n.t('baz') }
      +</Text>

      at testInvalidTemplate
(node_modules/eslint/lib/testers/rule-tester.js:514:28)
      at Context.RuleTester.it
(node_modules/eslint/lib/testers/rule-tester.js:539:25)
```